# Generated by Django 3.2.9 on 2021-11-12 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=200, verbose_name='Desc')),
                ('type', models.CharField(choices=[('Mobile', 'MOBILE'), ('Laptop', 'LAPTOP')], max_length=6)),
            ],
        ),
    ]
