# Generated by Django 3.2.9 on 2021-11-13 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Mob', 'MOBILE'), ('Lap', 'LAPTOP')], max_length=15),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processor', models.CharField(blank=True, max_length=50)),
                ('ram', models.CharField(blank=True, max_length=20)),
                ('screen_size', models.CharField(blank=True, max_length=20)),
                ('colour', models.CharField(blank=True, max_length=20)),
                ('hd_capacity', models.CharField(blank=True, max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
